version: "3"
services:
  lb:
    build: haproxy/.
    ports:
      - "80:80"
    links:
      - web1
      - web2
    depends_on:
      - web1
      - web2
    command: ["haproxy", "-f", "/usr/local/etc/haproxy/haproxy.cfg"]
  web1:
    build: app/.
    environment:
      - MYSQL_USER=appUser
      - MYSQL_PASS=appPassword
      - MYSQL_DB=dexma
      - MYSQL_HOST=db
      - FLASK_APP=app.py
    ports:
      - "5001:5001"
    links:
      - db
    depends_on:
      - db
    command: ["wait-for-it.sh", "db:3306", "--", "python", "-m", "flask", "run", "--host=0.0.0.0", "--port=5001"]
  web2:
    build: app/.
    environment:
      - MYSQL_USER=appUser
      - MYSQL_PASS=appPassword
      - MYSQL_DB=dexma
      - MYSQL_HOST=db
      - FLASK_APP=app.py
    ports:
      - "5002:5002"
    links:
      - db
    depends_on:
      - db
    command: ["wait-for-it.sh", "db:3306", "--", "python", "-m", "flask", "run", "--host=0.0.0.0", "--port=5002"]
  db:
    build: mysql/.
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=supersecure
      - MYSQL_DATABASE=dexma
      - MYSQL_USER=appUser
      - MYSQL_PASSWORD=appPassword
